from tools.get_aws_bill_api import get_aws_bill
from tools.get_azure_bill_api import get_azure_bill
from tools.get_gcp_bill_api import get_gcp_bill
from tools.cost_advisor import advise_on_aws_costs, advise_on_azure_costs, advise_on_gcp_costs
from langchain.llms import Ollama

llm = Ollama(model="mistral")

def generate_finops_report(query=""):
    # 1. Collect data
    aws = get_aws_bill()
    azure = get_azure_bill()
    gcp = get_gcp_bill()

    aws_advice = advise_on_aws_costs()
    azure_advice = advise_on_azure_costs()
    gcp_advice = advise_on_gcp_costs()

    # 2. Let LLM generate insight
    summary_prompt = (
        f"Given the cloud bills:\n"
        f"AWS: {aws}\nAzure: {azure}\nGCP: {gcp}\n"
        f"Write a brief executive summary highlighting patterns or concerns."
    )
    summary = llm(summary_prompt)

    # 3. Build report in Markdown
    report_md = f"""# ☁️ Finly Cloud Cost Report

## 🔍 Executive Summary
{summary}

---

## 💵 Cost Breakdown
- **AWS**: {aws}
- **Azure**: {azure}
- **GCP**: {gcp}

---

## 💡 Optimization Suggestions

### AWS
{aws_advice}

### Azure
{azure_advice}

### GCP
{gcp_advice}

---

_Report generated by Finly, your AI-powered FinOps Assistant_ 🤖
"""

    return {"output": report_md}
